// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.2
// source: build.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Build request
type BuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildLang     string                 `protobuf:"bytes,1,opt,name=buildLang,proto3" json:"buildLang,omitempty"`       // Build language
	BuildFiles    []*BuildFile           `protobuf:"bytes,2,rep,name=buildFiles,proto3" json:"buildFiles,omitempty"`     // Build files
	BuildRule     string                 `protobuf:"bytes,3,opt,name=buildRule,proto3" json:"buildRule,omitempty"`       // Build rule
	BuildPath     string                 `protobuf:"bytes,4,opt,name=buildPath,proto3" json:"buildPath,omitempty"`       // Build path
	BuildTargets  []string               `protobuf:"bytes,5,rep,name=buildTargets,proto3" json:"buildTargets,omitempty"` // Build targets
	BuildID       string                 `protobuf:"bytes,6,opt,name=buildID,proto3" json:"buildID,omitempty"`           // Build ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildRequest) Reset() {
	*x = BuildRequest{}
	mi := &file_build_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRequest) ProtoMessage() {}

func (x *BuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRequest.ProtoReflect.Descriptor instead.
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{0}
}

func (x *BuildRequest) GetBuildLang() string {
	if x != nil {
		return x.BuildLang
	}
	return ""
}

func (x *BuildRequest) GetBuildFiles() []*BuildFile {
	if x != nil {
		return x.BuildFiles
	}
	return nil
}

func (x *BuildRequest) GetBuildRule() string {
	if x != nil {
		return x.BuildRule
	}
	return ""
}

func (x *BuildRequest) GetBuildPath() string {
	if x != nil {
		return x.BuildPath
	}
	return ""
}

func (x *BuildRequest) GetBuildTargets() []string {
	if x != nil {
		return x.BuildTargets
	}
	return nil
}

func (x *BuildRequest) GetBuildID() string {
	if x != nil {
		return x.BuildID
	}
	return ""
}

// Build file
type BuildFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=filePath,proto3" json:"filePath,omitempty"` // File path
	FileData      []byte                 `protobuf:"bytes,2,opt,name=fileData,proto3" json:"fileData,omitempty"` // File data
	CheckSum      string                 `protobuf:"bytes,3,opt,name=checkSum,proto3" json:"checkSum,omitempty"` // File checksum
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildFile) Reset() {
	*x = BuildFile{}
	mi := &file_build_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildFile) ProtoMessage() {}

func (x *BuildFile) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildFile.ProtoReflect.Descriptor instead.
func (*BuildFile) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{1}
}

func (x *BuildFile) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *BuildFile) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *BuildFile) GetCheckSum() string {
	if x != nil {
		return x.CheckSum
	}
	return ""
}

// Build reply
type BuildReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildTargets  []*BuildTarget         `protobuf:"bytes,1,rep,name=buildTargets,proto3" json:"buildTargets,omitempty"` // Build targets
	BuildStatus   bool                   `protobuf:"varint,2,opt,name=buildStatus,proto3" json:"buildStatus,omitempty"`  // Build status
	BuildID       string                 `protobuf:"bytes,3,opt,name=buildID,proto3" json:"buildID,omitempty"`           // Build ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildReply) Reset() {
	*x = BuildReply{}
	mi := &file_build_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildReply) ProtoMessage() {}

func (x *BuildReply) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildReply.ProtoReflect.Descriptor instead.
func (*BuildReply) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{2}
}

func (x *BuildReply) GetBuildTargets() []*BuildTarget {
	if x != nil {
		return x.BuildTargets
	}
	return nil
}

func (x *BuildReply) GetBuildStatus() bool {
	if x != nil {
		return x.BuildStatus
	}
	return false
}

func (x *BuildReply) GetBuildID() string {
	if x != nil {
		return x.BuildID
	}
	return ""
}

// Build target
type BuildTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetPath    string                 `protobuf:"bytes,1,opt,name=targetPath,proto3" json:"targetPath,omitempty"` // Target path
	TargetData    []byte                 `protobuf:"bytes,2,opt,name=targetData,proto3" json:"targetData,omitempty"` // Target data
	Checksum      string                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`     // Target checksum
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildTarget) Reset() {
	*x = BuildTarget{}
	mi := &file_build_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildTarget) ProtoMessage() {}

func (x *BuildTarget) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildTarget.ProtoReflect.Descriptor instead.
func (*BuildTarget) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{3}
}

func (x *BuildTarget) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

func (x *BuildTarget) GetTargetData() []byte {
	if x != nil {
		return x.TargetData
	}
	return nil
}

func (x *BuildTarget) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

var File_build_proto protoreflect.FileDescriptor

var file_build_proto_rawDesc = string([]byte{
	0x0a, 0x0b, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x22, 0xd8, 0x01, 0x0a, 0x0c, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x4c, 0x61,
	0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x4c,
	0x61, 0x6e, 0x67, 0x12, 0x30, 0x0a, 0x0a, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x46, 0x69, 0x6c, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2e,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x0a, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x75,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x52,
	0x75, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x50, 0x61, 0x74, 0x68,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x22, 0x0a, 0x0c, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x44,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x44, 0x22,
	0x5f, 0x0a, 0x09, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x75, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x75, 0x6d,
	0x22, 0x80, 0x01, 0x0a, 0x0a, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x36, 0x0a, 0x0c, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2e, 0x42, 0x75,
	0x69, 0x6c, 0x64, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x0c, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x75, 0x69,
	0x6c, 0x64, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x75, 0x69, 0x6c,
	0x64, 0x49, 0x44, 0x22, 0x69, 0x0a, 0x0b, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x61,
	0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x32, 0x47,
	0x0a, 0x0c, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37,
	0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x13, 0x2e, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x11, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x28, 0x01, 0x30, 0x01, 0x42, 0x1e, 0x5a, 0x1c, 0x64, 0x69, 0x73, 0x74, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x2f, 0x62, 0x6f, 0x6f, 0x6e, 0x67, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_build_proto_rawDescOnce sync.Once
	file_build_proto_rawDescData []byte
)

func file_build_proto_rawDescGZIP() []byte {
	file_build_proto_rawDescOnce.Do(func() {
		file_build_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_build_proto_rawDesc), len(file_build_proto_rawDesc)))
	})
	return file_build_proto_rawDescData
}

var file_build_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_build_proto_goTypes = []any{
	(*BuildRequest)(nil), // 0: build.BuildRequest
	(*BuildFile)(nil),    // 1: build.BuildFile
	(*BuildReply)(nil),   // 2: build.BuildReply
	(*BuildTarget)(nil),  // 3: build.BuildTarget
}
var file_build_proto_depIdxs = []int32{
	1, // 0: build.BuildRequest.buildFiles:type_name -> build.BuildFile
	3, // 1: build.BuildReply.buildTargets:type_name -> build.BuildTarget
	0, // 2: build.BuildService.SendBuild:input_type -> build.BuildRequest
	2, // 3: build.BuildService.SendBuild:output_type -> build.BuildReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_build_proto_init() }
func file_build_proto_init() {
	if File_build_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_build_proto_rawDesc), len(file_build_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_build_proto_goTypes,
		DependencyIndexes: file_build_proto_depIdxs,
		MessageInfos:      file_build_proto_msgTypes,
	}.Build()
	File_build_proto = out.File
	file_build_proto_goTypes = nil
	file_build_proto_depIdxs = nil
}
